doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        types:
            email:  App\Domain\Common\Type\EmailType
            password:  App\Domain\Common\Type\PasswordType
            date_range:  App\Domain\Common\Type\DateRangeType
            position: App\Domain\Common\Type\PositionType
            time: App\Domain\Common\Type\TimeType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                alias: App
